## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [2]:
# 1) (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.

df_matp = 100 * df_mat / 24 
df_porp = 100 * df_por / 18
df_geop = 100 * df_geo / 8
df_ingp = 100 * df_ing / 8
df_hisp = 100 * df_his / 8
df_fisp = 100 * df_fis / 12
df_quip = 100 * df_qui / 12

In [3]:
# 2) (operações entre *DataFrames) Calcule o total de acertos de cada aluno.
pd.set_option('display.max_rows', 10)
df = pd.DataFrame()
df['total_aluno']= df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui
df

    total_aluno
0            35
1            48
2            50
3            32
4            30
..          ...
95           34
96           27
97           40
98           40
99           42

[100 rows x 1 columns]

In [4]:
# 3) Calcule o porcentual geral de cada aluno. 
total_questoes = 24 + 18 + 8 + 8 + 8 + 12 + 12

df['percentual_geral(%)'] = 100 * df['total_aluno'] / total_questoes
df

    total_aluno  percentual_geral(%)
0            35            38.888889
1            48            53.333333
2            50            55.555556
3            32            35.555556
4            30            33.333333
..          ...                  ...
95           34            37.777778
96           27            30.000000
97           40            44.444444
98           40            44.444444
99           42            46.666667

[100 rows x 2 columns]

In [5]:
# 4) Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?
qntd_aprovados = (df['total_aluno'] > 45).sum()
qntd_aprovados

31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [6]:
# 1. seu código aqui
pd.set_option('display.max_rows', 5)

df_desq = df_mat[df_mat['Qt_acertos'] == 0] + df_fis[df_fis['Qt_acertos'] == 0] + df_qui[df_qui['Qt_acertos'] == 0]
df_desq = df_desq.fillna(0)

df_desq

    Qt_acertos
3          0.0
6          0.0
..         ...
94         0.0
98         0.0

[23 rows x 1 columns]

In [7]:
#2. Quantos são esses alunos?
df_desq.count()

Qt_acertos    23
dtype: int64

In [8]:
df_desq.drop(columns=['Qt_acertos'], inplace=True)

In [9]:
#3. Qual a média desses alunos em história e geografia?
pd.set_option('display.max_rows', 6)

df_desq['Acertos_historia'] = df_his.loc[df_desq.index]
df_desq['Acertos_geografia'] = df_geo.loc[df_desq.index]
df_desq

    Acertos_historia  Acertos_geografia
3                  0                  3
6                  5                  7
10                 1                  3
..               ...                ...
92                 1                  1
94                 1                  2
98                 5                  3

[23 rows x 2 columns]

In [10]:
#4. Monte um DataFrame com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.
df_qualif = df[(df['total_aluno'] > 45) & (~df.index.isin(df_desq.index))]
df_qualif

    total_aluno  percentual_geral(%)
1            48            53.333333
2            50            55.555556
5            50            55.555556
..          ...                  ...
81           55            61.111111
88           50            55.555556
93           56            62.222222

[26 rows x 2 columns]

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [11]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-4953a12d-d63a-41ce-b3d6-9efbd4964689.c000.csv'
pd.set_option('display.max_rows', 4)

df_covid = pd.read_csv(arquivo, sep=';')
df_covid

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,20c219e2-fc7e-40e6-9de3-360d18ad75c0-i0b0,61839412611ea4d505c00317840fe43df823be20ef2192...,52,1969-05-23,M,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,217VCD230Z,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-09-22,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
1,ecd79473-4aa6-4d7e-bfb8-2fb7280a50fc-i0b0,47062cd51d08fce8221a47f22d99ad61c9e48f3c8af789...,24,1997-06-17,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,2.0,Faixa Etária,FL1939,PFIZER,Organization/28290,2022-01-24,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379756,fdc5ecb3-11d6-48c5-b27a-eec761e94aed-i0b0,cbdecabceacdf87b0f538ecfc0d5ff0b1f46d188abe12a...,5,2016-11-27,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,NaN,NaN,FN4073,PFIZER - PEDIÁTRICA,28290,2022-07-20,2ª Dose,99,COVID-19 PEDIÁTRICA - PFIZER COMIRNATY,Novo PNI
379757,fdf4daec-a7e0-481d-9e92-b6cf11c02a1d-i0b0,18b1ccf00bc06d51ec51142be4443b4d539427d7816cef...,16,2005-10-04,F,3,PARDA,120020.0,10.0,CRUZEIRO DO SUL,...,114.0,Outros,FF8848,PFIZER,Organization/00394544000851,2021-11-13,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [12]:
# 1) Sua solução aqui
num_entries = len(df_covid)
num_entries

379758

In [13]:
# 2)
vacinados_arr = df_covid['paciente_id'].nunique()
vacinados_arr

311605

In [14]:
# 3)
df_prim_dose = df_covid[df_covid['vacina_descricao_dose'] == '1ª Dose']
print(df_prim_dose['paciente_id'].nunique())

141928

In [15]:
# 4) solução alternativa
df_nao_adulto = df_covid[df_covid['paciente_idade'] < 18]
len(df_nao_adulto)

73108

In [16]:
print(df_covid.columns)

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [17]:
# 5)
print(df_covid['estabelecimento_municipio_codigo'].nunique())

22

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [18]:
# 1)
df_nao_adulto = df_covid[df_covid['paciente_idade'] < 18]
df_nao_adulto

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
3,ecdfc4c3-3eb5-45ec-aa72-6d41961096fb-i0b0,6ff26e05df4916733b3fc08e151e04801ce6614d1ae0e9...,7,2014-08-30,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,NaN,NaN,FN5988,Pendente Identificação,Organization/28290,2022-04-08,1ª Dose,99,COVID-19 PEDIÁTRICA - PFIZER COMIRNATY,Novo PNI
13,ed6f56ea-71be-4cca-88d4-40feaf102224-i0b0,402073067ab0c128e56f14a7d2f4a6b1bb6f86ad550bd3...,17,2003-11-07,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FF8842,PFIZER,Organization/28290,2021-10-01,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379756,fdc5ecb3-11d6-48c5-b27a-eec761e94aed-i0b0,cbdecabceacdf87b0f538ecfc0d5ff0b1f46d188abe12a...,5,2016-11-27,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,NaN,NaN,FN4073,PFIZER - PEDIÁTRICA,28290,2022-07-20,2ª Dose,99,COVID-19 PEDIÁTRICA - PFIZER COMIRNATY,Novo PNI
379757,fdf4daec-a7e0-481d-9e92-b6cf11c02a1d-i0b0,18b1ccf00bc06d51ec51142be4443b4d539427d7816cef...,16,2005-10-04,F,3,PARDA,120020.0,10.0,CRUZEIRO DO SUL,...,114.0,Outros,FF8848,PFIZER,Organization/00394544000851,2021-11-13,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [19]:
# 2)
df_nao_adulto.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [20]:
# 3)
df_nao_adulto['vacina_categoria_nome'].nunique()

13

In [22]:
# 4)
columns_to_copy = ['estabelecimento_razaoSocial',
                   'estabelecimento_valor',
                   'estalecimento_noFantasia',
                   'estabelecimento_municipio_codigo',
                   'estabelecimento_municipio_nome',
                   'estabelecimento_uf']

# 5)
df_estabelecimento = df_nao_adulto.loc[:, columns_to_copy]

In [23]:
df_estabelecimento

,estabelecimento_razaoSocial,estabelecimento_valor,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
3,PREFEITURA MUNICIPAL DE RIO BRANCO,6917291,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
13,PREFEITURA MUNICIPAL DE RIO BRANCO,6917291,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
...,...,...,...,...,...,...
379756,PREFEITURA MUNICIPAL DE RIO BRANCO,6917291,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
379757,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,6159087,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC

In [25]:
# 6) Aplique o método .drop_duplicates e crie uma lista com uma linha para cada estabelecimento
df_estabelecimento.drop_duplicates()

,estabelecimento_razaoSocial,estabelecimento_valor,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
3,PREFEITURA MUNICIPAL DE RIO BRANCO,6917291,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
28,PREFEITURA MUNICIPAL DE XAPURI,2001217,UNIDADE SAUDE DA FAMILIA JOSE FADUL,120070,XAPURI,AC
...,...,...,...,...,...,...
222197,PREFEITURA MUNICIPAL DE JORDAO,7123043,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC
253671,SECRETARIA MUNICIPAL DE SAUDE DE BRASILEIA,2001357,ESF PEDRO OLIVEIRA DE SOUZA,120010,BRASILEIA,AC